### ISSUE TITLE
program is broken

### ISSUE THREAD

**Issue by N-Coder** [fknorr/studip-client#18]
It fails on this folder
![screenshot from 2017-04-27 14-28-50](https://cloud.githubusercontent.com/assets/1306276/25483408/f21cd70a-2b55-11e7-97e8-0fe5ae661dfe.png)

```
Using last sync directory /home/niko/Sync/Uni ...
Traceback (most recent call last):
  File "/usr/bin/studip", line 9, in <module>
    load_entry_point('studip-client==1.2', 'console_scripts', 'studip')()
  File "/usr/lib/python3.5/site-packages/studip_client-1.2-py3.5.egg/studip/application.py", line 414, in main
    app.run()
  File "/usr/lib/python3.5/site-packages/studip_client-1.2-py3.5.egg/studip/application.py", line 404, in run
    self.edit_views()
  File "/usr/lib/python3.5/site-packages/studip_client-1.2-py3.5.egg/studip/application.py", line 284, in edit_views
    view_sync = ViewSynchronizer(self.sync_dir, self.config, self.database, view)
  File "/usr/lib/python3.5/site-packages/studip_client-1.2-py3.5.egg/studip/views.py", line 51, in __init__
    select_sync_no=False):
  File "/usr/lib/python3.5/site-packages/studip_client-1.2-py3.5.egg/studip/database.py", line 211, in list_files
    for i, j, s, c, o, path, n, e, a, d, t, y in rows ]
  File "/usr/lib/python3.5/site-packages/studip_client-1.2-py3.5.egg/studip/database.py", line 211, in <listcomp>
    for i, j, s, c, o, path, n, e, a, d, t, y in rows ]
  File "/usr/lib64/python3.5/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib64/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    ["Symposium \\"Integration durch Bildung\\"", "Protokolle Orga-Treffen"]
                             ^
SyntaxError: invalid syntax

```

**Comment by fknorr** [comment]
Fixed in ae82ed6 .
