### ISSUE TITLE
Parser-Fehler bei Veranstaltungen mit neuem [versteckt] tag

### ISSUE THREAD

**Issue by N-Coder** [fknorr/studip-client#23]
z.B. bei "StudIP Sync Testers (Studien-/Arbeitsgruppe) [versteckt]"
```
Traceback (most recent call last):
  File "/usr/bin/studip", line 9, in <module>
    load_entry_point('studip-client==1.2', 'console_scripts', 'studip')()
  File "/usr/lib/python3.5/site-packages/studip_client-1.2-py3.5.egg/studip/application.py", line 414, in main
    app.run()
  File "/usr/lib/python3.5/site-packages/studip_client-1.2-py3.5.egg/studip/application.py", line 394, in run
    self.update_database()
  File "/usr/lib/python3.5/site-packages/studip_client-1.2-py3.5.egg/studip/application.py", line 172, in update_database
    self.session.update_metadata()
  File "/usr/lib/python3.5/site-packages/studip_client-1.2-py3.5.egg/studip/session.py", line 113, in update_metadata
    remote_courses = parse_course_list(overview_page)
  File "/usr/lib/python3.5/site-packages/studip_client-1.2-py3.5.egg/studip/parsers.py", line 222, in parse_course_list
    return create_parser_and_feed(CourseListParser, html).courses
  File "/usr/lib/python3.5/site-packages/studip_client-1.2-py3.5.egg/studip/parsers.py", line 37, in create_parser_and_feed
    parser.feed(html)
  File "/usr/lib64/python3.5/html/parser.py", line 111, in feed
    self.goahead(0)
  File "/usr/lib64/python3.5/html/parser.py", line 173, in goahead
    k = self.parse_endtag(i)
  File "/usr/lib64/python3.5/html/parser.py", line 421, in parse_endtag
    self.handle_endtag(elem.lower())
  File "/usr/lib/python3.5/site-packages/studip_client-1.2-py3.5.egg/studip/parsers.py", line 201, in handle_endtag
    name, type = COURSE_NAME_TYPE_RE.match(full_name).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

Möglicher fix: nur den Text des a-Tags parsen:
```
<td style="text-align: left">
    <a href="https://studip.uni-passau.de/studip/seminar_main.php?auswahl=af410645013dd028994c703c40e1f816"
       style="color: red;" contextmenu="menu-af410645013dd028994c703c40e1f816">
        StudIP Sync Testers (Studien-/Arbeitsgruppe)
    </a>
    [versteckt] <span class="tooltip tooltip-icon " data-tooltip="" title=""></span>
</td>
```

**Comment by fknorr** [comment]
Duplicate of #20, fixed in v1.3
