### ISSUE TITLE
SQLite error directly after installation

### ISSUE THREAD

**Issue by Claudio-S** [fknorr/studip-client#25]
Just after installing via setup.py and giving the credentials, the following error occures while running "studip sync":

`root@v-1:/home/syncthing/studip-sync/.studip# studip sync
Using last sync directory /home/syncthing/studip-sync ...
Traceback (most recent call last):
  File "/usr/local/bin/studip", line 11, in <module>
    load_entry_point('studip-client==1.3', 'console_scripts', 'studip')()
  File "/usr/local/lib/python3.4/dist-packages/studip_client-1.3-py3.4.egg/studip/application.py", line 414, in main
    app.run()
  File "/usr/local/lib/python3.4/dist-packages/studip_client-1.3-py3.4.egg/studip/application.py", line 394, in run
    self.update_database()
  File "/usr/local/lib/python3.4/dist-packages/studip_client-1.3-py3.4.egg/studip/application.py", line 172, in update_database
    self.session.update_metadata()
  File "/usr/local/lib/python3.4/dist-packages/studip_client-1.3-py3.4.egg/studip/session.py", line 110, in update_metadata
    self.db.update_semester_list(semester_list.semesters)
  File "/usr/local/lib/python3.4/dist-packages/studip_client-1.3-py3.4.egg/studip/database.py", line 165, in update_semester_list
    """, (s.__dict__ for s in semesters))
  File "/usr/local/lib/python3.4/dist-packages/studip_client-1.3-py3.4.egg/studip/database.py", line 158, in query_multiple
    self.conn.cursor().executemany(sql, args)
sqlite3.OperationalError: no such table: semesters`

**Comment by Claudio-S** [comment]
fixed it by doing "studip clear-cache" and recreating the sync directory
